<p class="last-updated">Last Updated: {{ page.updated|date('F j, o') }}</p>

<footer>

  <ul id="nav">
    <li>Menu Item 1</li>
    <li><a href="">Newsroom</a></li>
    <li>Menu Item 3</li>
    <li>Menu Item 4</li>
    <li>Menu Item 5</li>
  </ul>

  <div class="mission-statement">
    <p>The mission of the U.S. Fish and Wildlife Service is working with others to conserve, protect, and enhance fish, wildlife, plants, and their habitats for the continuing benefit of the American people.</p>
  </div>

  <ul class="external-links">
    <li><a href="http://www.fws.gov/">U.S. Fish and Wildlife Service Home Page</a></li>
    <li><a href="http://www.doi.gov/">Department of the Interior</a></li>
    <li><a href="http://www.usa.gov/">USA.gov</a></li>
    <li><a href="http://www.fws.gov/help/about_us.html">About the U.S. Fish and Wildlife Service</a></li>
    <li><a href="http://www.fws.gov/help/accessibility.html">Accessibility</a></li>
    <li><a href="http://www.fws.gov/help/policies.html">Privacy</a></li>
    <li><a href="http://www.fws.gov/help/notices.html">Notices</a></li>
    <li><a href="http://www.fws.gov/help/disclaimer.html">Disclaimer</a></li>
    <li><a href="http://www.fws.gov/irm/bpim/foia.html">FOIA</a></li>
  </ul>
</footer>